Use pure Python implementation of MD4
Using hashlib to do this lead to an exception on my system:

```
Traceback (most recent call last):
  File "/usr/lib/python3.10/hashlib.py", line 160, in __hash_new
    return _hashlib.new(name, data, **kwargs)
ValueError: [digital envelope routines] unsupported

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/avollmer/.local/bin/hashcathelper", line 33, in <module>
    sys.exit(load_entry_point('hashcathelper', 'console_scripts', 'hashcathelper')())
  File "/home/avollmer/gitea/hashcathelper/hashcathelper/__main__.py", line 6, in main
    args.func(args)
  File "/home/avollmer/gitea/hashcathelper/hashcathelper/subcommands/analytics.py", line 120, in analytics
    report = create_report(
  File "/home/avollmer/gitea/hashcathelper/hashcathelper/analytics.py", line 414, in create_report
    details = gather_details(
  File "/home/avollmer/gitea/hashcathelper/hashcathelper/analytics.py", line 466, in gather_details
    hash_map = {
  File "/home/avollmer/gitea/hashcathelper/hashcathelper/analytics.py", line 467, in <dictcomp>
    get_nthash(u.password.encode()).decode(): u.password
  File "/home/avollmer/gitea/hashcathelper/hashcathelper/utils.py", line 19, in get_nthash
    result = hashlib.new(
  File "/usr/lib/python3.10/hashlib.py", line 166, in __hash_new
    return __get_builtin_constructor(name)(data)
  File "/usr/lib/python3.10/hashlib.py", line 123, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type md4
```

Presumably because of this: https://bugzilla.redhat.com/show_bug.cgi?id=2054702

Apparently modern OpenSSL builds don't support legacy algorithms anymore. So we
switch to a pure Python implementation.