Convert everything to string when printing table
This caused issues on hashcat01:

```
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/cracker/.local/bin/hashcathelper/__main__.py", line 3, in <module>
  File "/home/cracker/.local/bin/hashcathelper/hashcathelper/__main__.py", line 6, in main
  File "/home/cracker/.local/bin/hashcathelper/hashcathelper/subcommands/analytics.py", line 74, in analytics
  File "/home/cracker/.local/bin/hashcathelper/hashcathelper/reporting.py", line 42, in export
  File "/home/cracker/.local/bin/hashcathelper/hashcathelper/reporting.py", line 148, in _export_text
  File "/home/cracker/.local/bin/hashcathelper/hashcathelper/reporting.py", line 42, in export
  File "/home/cracker/.local/bin/hashcathelper/hashcathelper/reporting.py", line 101, in _export_text
  File "/home/cracker/.local/bin/hashcathelper/hashcathelper/reporting.py", line 42, in export
  File "/home/cracker/.local/bin/hashcathelper/hashcathelper/reporting.py", line 244, in _export_text
  File "/home/cracker/.local/bin/hashcathelper/hashcathelper/reporting.py", line 208, in _export_text
TypeError: object of type 'int' has no len()
```